### ISSUE TITLE
How to interpolate {build.number} to actual build number?

### ISSUE THREAD

**Issue by jonespen** [oledid/teamcity-build-number-cli#1]
Hey!

When using this, {build.number} is not interpolated/replaced, resulting in something like this: `0.4.2.{build.number}`

First I run a npm script with `node ./node_modules/teamcity-build-number-cli/src/cli`, then a powershell build step which looks like this
```
$buildNumber = "%build.number%" 

Write-Host "setting env.APP_VERSION to $buildNumber"
Write-Host "##teamcity[setParameter name='env.APP_VERSION' value='$buildNumber']"
```

I'm no powershell and/or teamcity expert, so a nudge in the right direction would be nice :)

**Comment by oledid** [comment]
Hi

I have set the "Build number format" in the teamcity build configuration settings to `%build.counter%`, which I believe is the default.

When teamcity starts building, the internal build number (%build.counter%) displays first, but when the cli eventuelly gets called the build number in TeamCity changes to {package.version}.%build.counter%.

Example:
* %build.counter% is 5
* package.json is version 1.2.3
* Teamcity starts building, shows it is building `#5`
* The cli outputs `##teamcity[buildNumber '1.2.3.{build.number}']`
* Teamcity parses the command and replaces {build.number} with %build.counter%
* Teamcity changes the number of the build to `#1.2.3.5`

I hope this helps, and I will update the readme. Sorry for taking so long to respond, but you are the first to create an issue in my personal repositories. :) Thanks.

**Comment by oledid** [comment]
Updated the readme. I might have explained things better there. Thanks for your feedback, closing the issue.

**Comment by jonespen** [comment]
Sorry, I wasn't clear enough, the part with TeamCity actually works great.

![image](https://cloud.githubusercontent.com/assets/230841/21137625/a508bc94-c12a-11e6-8245-698b18e586e3.png)

The problem is, I want to use the same build number (1.0.2.143) in my app as well. Maybe this is out of scope of this script, but I was hoping that 
```
$buildNumber = "%build.number%" 

Write-Host "setting env.APP_VERSION to $buildNumber"
Write-Host "##teamcity[setParameter name='env.APP_VERSION' value='$buildNumber']"
```
would set the env parameter `APP_VERSION` to `1.0.2.143`, but instead it is set to `1.0.2.{build.number}`, probably because TeamCity doesn't interpolate it.

**Comment by oledid** [comment]
@jonespen Haven't tried this. But maybe it is already set in env as BUILD_NUMBER after the cli has run?

https://confluence.jetbrains.com/display/TCD9/Predefined+Build+Parameters

**Comment by oledid** [comment]
@jonespen I got curious and tried to solve the problem.

The solution is here:
```powershell
# teamcity-build-script.ps1

npm install --save-dev teamcity-build-number-cli

# finding the buildIterator
$buildIterator = $env:build_number
write-host "`$env:build_number is '$buildIterator'"

# run the cli and store the output
$cliOutput = ./node_modules/.bin/teamcity-build-number.cmd | out-string

# output the cli's output to teamcity
write-host $cliOutput

$stringFromCliOutput = [regex]::match($cliOutput, "(\d\.\d\.\d\.{build.number})").Groups[1].Value
$wantedResult = ($stringFromCliOutput -replace "{build.number}", $buildIterator)
write-host "What you want is '$wantedResult'."

write-host "##teamcity[setParameter name='env.APP_VERSION' value='$wantedResult']"
```
