### ISSUE TITLE
'teamcity-build-number' is not recognized

### ISSUE THREAD

**Issue by Michael-McD** [oledid/teamcity-build-number-cli#2]
Hi,
Having installed `teamcity-build-number` globally on the build agent and adding a command line build step in TC to execute 'teamcity-build-number' the step fails with:
`'teamcity-build-number' is not recognized as an internal or external command`
however if I run this on the build server itself (after a reboot) it works as expected i.e. returns the package no. + TC variable.
Am I doing something wrong?

**Comment by oledid** [comment]
Hi @Michael-McD 

The build agent does not find `teamcity-build-number` in the path. You can try rebooting the build agent, or specifying the full path in the build step, which might be something like `C:\Program Files\nodejs\teamcity-build-number.cmd`

To find the full path it is probably where npm is, so run `where.exe npm` to find it.

Tell me if this fixes your problem or not.

**Comment by Michael-McD** [comment]
Added it to the path and all is well.

Thanx,
Michael
ps didn't know about where.exe very useful ta again.
