### ISSUE TITLE
Artifact Name Using teamcity build Number

### ISSUE THREAD

**Issue by Jebaseelanravi** [oledid/teamcity-build-number-cli#4]
Hi @oledid 

I tried to change the build number using teamcity-build-number-cli,It is working fine.But when i try to export the Artifact using the %build.number%.I am not getting the same number as in Build number for the build.

For example.
My artifact path:
%project_path%\dist\*.crx=>sourecplugin-%build.number%.crx

Expected:
sourceplugin-0.3.0.46.crx
46 is build counter value

Actual:
sourceplugin-0.3.0.{build_number}.crx

**Comment by oledid** [comment]
Hi

You can probably work something out using `%build.counter%` instead of `%build.number%` in the artifacts path. Or combine them.

**Comment by Jebaseelanravi** [comment]
Hi @oledid 

Thank s for the response.
I have tried out the suggestions you have give.

When I am using %build.counter% I am getting sourceplugin.46.crx
When I am using %build.counter% I am getting sourceplugin-0.3.0.{build_number}.crx
When I am combined  both of them I am getting sourceplugin-0.3.0.{build_number}.46.crx

Actual output I am expecting

sourceplugin-0.3.0.46.crx
